### ISSUE TITLE
Flow types not packed into jest-enzyme

### ISSUE THREAD

**Issue by pascalduez** [blainekasten/enzyme-matchers#107]
Hi,

just did a fresh install of `jest-enzyme` and the `types` folder is not packed with the package, only the `lib` folder is present. Same for the `enzyme-matchers` package.

Not sure what the initial goal for 20682e14 was actually.

**Comment by blainekasten** [comment]
It was an ignorant change. I didn't think about it's file resolution..

We just released an update `3.3.0` that seems like it's fixing flow for most people. Can you test it out?

**Comment by pascalduez** [comment]
From `3.3.0` Flow won't complain on source files, but won't find any type information since the `lib` folder is compiled sources.

If you wan't to ship types with the package, `flow-copy-sources` could be a solution.

For now I'm relying on the `flow-typed` [definitions](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/jest_v20.x.x/flow_v0.33.x-/jest_v20.x.x.js#L109-L129) ;)

**Comment by blainekasten** [comment]
Oh awesome! I didn't know they had those definitions in `flow-typed` That's great!

But yeah, I think we should ship the `types`. It could help and just seems like the right call. Are you willing to submit a PR to implement `flow-copy-sources` into each package?
