### ISSUE TITLE
index.d.ts isn't shipped with 3.3.0

### ISSUE THREAD

**Issue by paibamboo** [blainekasten/enzyme-matchers#110]
![image](https://user-images.githubusercontent.com/13611391/27522664-06cadb2c-5a52-11e7-9f1c-5056aac7eb26.png)

moved to somewhere else?

**Comment by blainekasten** [comment]
Shoot. My bad, looks like this happened from #77 which helped flowtype work.

I think we just need the `.d.ts` file from `src` to end up in the `lib` folder. Can you add `--copy-files` to the `babel` build step? That should do it.
