### ISSUE TITLE
`toHaveProp()` should maybe compare `undefined` values?

### ISSUE THREAD

**Issue by jcarlson** [blainekasten/enzyme-matchers#111]
Consider a test that looks something like the following:

```jsx
class MyComponent extends React.Component {
  render () {
    return <div>{ this.props.name }</div>
  }
}

describe('MyComponent', () => {
  it('has name prop', () => {
    let props = { name: 'Mr. Foobar' }
    let wrapper = shallow(<MyComponent { ...props } />)
    expect(wrapper).toHaveProp('name', props.nameTypo)
  })
})
```

In this case, the test passes, even though there is an obvious typo in the matcher's arguments: `.toHaveProp('name', props.nameTypo)`.

The _intent_ here is obvious: the component should have a prop called `name` with a value of `'Mr. Foobar'`. In practice, though, because of the typo, the matcher simply checked that the prop existed, and stopped short of comparing the component's actual value for `name` with the expected value (of `undefined`).

I think this might be a case where the matcher _should_ have compared the values. It may be necessary to consider `arguments.length` to determine if a value comparison is required, not whether the `propValue === undefined`. Doing so should preserve the ability to call the matcher with one arg (`.toHaveProp('foo')`) as well as catch programmer mistakes like the case outlined above.

**Comment by blainekasten** [comment]
That's a really good point. That looks like a bug to me. We should be able to validate this like so:


```js
function toHaveProp(propKey, value) {
  if (arguments.length === 2 && value === undefined) {
    // don't ignore the prop.
  }
}
```

Mind submitting a PR to fix this? I would be curious if `toHaveState` and `toHaveStyle` have the same issues. If you do this could you try and make it modular to work on all 3 (assuming they are affected)
