### ISSUE TITLE
Use of jasmine matcher as value of toHaveProp()

### ISSUE THREAD

**Issue by sfargier** [blainekasten/enzyme-matchers#114]
I am trying to update a project that uses the old 1.2.0 version of jasmine-enzyme and I encountered a breaking change that I don't see mentioned in the change-log (this is jasmine specific).
The toHaveProp() method does not work aymore when jasmine core matchers are used as value.
```javascript
class MyComponent extends React.Component {
	render () {
		return <div name="whatever" />;
	}
}

it( 'toHaveProp()  with jasmine matchers as value', () => {
	const wrapper = shallow(<MyComponent />);
        // This one works:
	expect( wrapper ).toHaveProp( 'name', 'whatever' );
	// This one fails with 2.0.0 and above:
	expect( wrapper ).toHaveProp( 'name', jasmine.any( String ) );
} );
```

1.2.0 works, but 2.0.0 and 3.4.0 gives the same error:
```javascript
Expected <MyComponent> "name" prop values to match (using npm.deepEqualIdent) but they didn't.
```

Should this be working or did you drop support for this specific stuff at one point ?
I have not  used jest yet, so I don't know if there is any equivalent.

Thanks !

**Comment by blainekasten** [comment]
Did you update `enzyme` as well?

**Comment by sfargier** [comment]
Yes, I am using enzyme 2.9.1 (latest one at the moment).

I checked the code from jasmine-enzyme before opening the issue, and I guess the change comes from using the deepEqualIdent npm module instead of the util.equals/customEqualityTesters tooling that jasmine provides to the custom matchers (this happened in 2.0.0 when the module was reorganized). I don't know if putting this behaviour back would be easy while supporting both jest and jasmine though, so that was more of an open question to see your opinion.

**Comment by blainekasten** [comment]
Ohhh, I see where the issue is now. I misunderstood it at first glance.

I am partial to jest, but this library supports jasmine and should the best it could. So I would consider this a bug and be open to a PR if we can keep parity.

**Comment by sfargier** [comment]
I was hoping to work on a PR today, but things have been too busy. I haven't given up on the idea, but this will take a little time :)

**Comment by sfargier** [comment]
Finally got time to work on this :)
PR submitted, let me know if that's fine with you.
