### ISSUE TITLE
Typescript can't find index.d.ts

### ISSUE THREAD

**Issue by paibamboo** [blainekasten/enzyme-matchers#124]
index.d.ts was in src folder in 3.2.0 but in 3.5.1 it's in lib folder and Typescript cannot find the definitions anymore.

Also @types/jest defines Matchers as `interface Matchers<R>` but jest-enzyme defines Matchers as `interface Matchers`. This causes Typescript to throw error `All declaration of Matchers must have identical type parameters`

**Comment by blainekasten** [comment]
@paibamboo Sorry about this. I don't personally use typescript so I've been relying on community support to get this working. I want to cc some of the people who have worked on it so we can figure out what needs to be done.

@Dean177 @pascalduez @pselden

**Comment by blainekasten** [comment]
@paibamboo can you try `3.5.3`?

**Comment by Dean177** [comment]
I will have a look tonight and try to resolve

**Comment by paibamboo** [comment]
@blainekasten index.d.tx is now found. Another part is the type def itself which this [pull request](https://github.com/blainekasten/enzyme-matchers/pull/130) should solve it.
