### ISSUE TITLE
mapWrappersHTML() throws exception when a component has object property

### ISSUE THREAD

**Issue by chris-divvito** [blainekasten/enzyme-matchers#135]
Hello,

I've found that when a component has an object property, mapWrappersHTML() throws an exception like "TypeError: 'Symbol(Symbol.toPrimitive)' returned for property 'Symbol(Symbol.toPrimitive)' of object '[object Object]' is not a function"

This is because it attempts to run `${key}="${props[key]}"` and fails to interpolate the object.

This is seen, for example, when running .toBePresent() against more than one result().

I'm not sure I see the benefit of mapWrappersHTML() having all that complexity - couldn't it essentially perform the same as the single node case in printHTMLForWrapper()?

**Comment by chris-divvito** [comment]
On further inspection, this isn't a problem for any old object - this is specific to Proxy's. This is a problem if you are using identity-obj-proxy to mock, eg. Theme objects from SCSS files.

**Comment by blainekasten** [comment]
If you can find a fix for Proxy's that doesn't break other tests I'd be happy to take it.

The `mapWrappersHTML` fn is really nice to properly print things in different states and trim down the output. So we want to keep it. But interested in a fix for sure!
