### ISSUE TITLE
Whats the difference between jest-enzyme vs installing jest & enzyme

### ISSUE THREAD

**Issue by darewreck54** [blainekasten/enzyme-matchers#154]
Hi,

I was wondering what the difference is between installing jest-enzyme vs. just installing jest and enzyme separately.

Thanks,
Derek

**Comment by blainekasten** [comment]
Hey @darewreck54 

`jest-enzyme` compliments `jest` + `enzyme`. To explain a little more:

`jest` is a test runner.
`enzyme` is a utility library for testing React components.

`jest-enzyme` is a set of matchers which are added to `jest` to simplify using `enzyme`.

Here is an example with and without this library.

```jsx
// without jest-enzyme
const wrapper = mount(<Component className="bar" />);

expect(wrapper.props().className).toBe('bar');
```

```jsx
// WITH jest-enzyme
const wrapper = mount(<Component className="bar" />);

expect(wrapper).toHaveProps('className', 'bar');
```

**Comment by blainekasten** [comment]
I'm going to close this issue as there isn't anything for me to action on. Feel free to keep asking questions here though!
