### ISSUE TITLE
parameter `str`. Missing annotation

### ISSUE THREAD

**Issue by gibbok** [blainekasten/enzyme-matchers#155]
I use the following dependencies in package.json:

>  "devDependencies": {
>     "enzyme": "2.9.1",
>     "flow-bin": "0.54.1"
> }

When running in terminal:

`npm run flow`

I get the following error:

> Error: node_modules/enzyme-matchers/lib/utils/colors.js.flow:17
 17:   colorFns[color] = str => {
                         ^^^ parameter `str`. Missing annotation

Desired behavior:
Flow server should be launched.

As workaround I am currently using in file .flowconfig the following ignore rules, but I suspect a proper flow annotation should be added in `enzyme-matchers` itself.

> [ignore]
> .*/node_modules/enzyme-matchers/.*
> .*/node_modules/jest-enzyme/.*

**Comment by blainekasten** [comment]
Thanks for the report, #151 seems like the fix. I'll ship a patch in a little bit.

**Comment by blainekasten** [comment]
Try `3.8.3`
