### ISSUE TITLE
jest-enzyme why use beforeEach?

### ISSUE THREAD

**Issue by mockdeep** [blainekasten/enzyme-matchers#157]
I was just looking over the code and was wondering why the matchers are added [inside a `beforeEach` hook](https://github.com/blainekasten/enzyme-matchers/blob/master/packages/jest-enzyme/src/index.js#L20). Doesn't this rebuild the matchers before every single test? Maybe I'm missing something, and the performance implications are probably trivial, but I think `expect.extends` should be available at the global scope.

**Comment by blainekasten** [comment]
@mockdeep I think that's some legacy code from when this and jasmine-enzyme were the same library..

That's a really good catch and I believe you are absolutely right. Would you mind putting up a PR and testing it out to confirm?

**Comment by mockdeep** [comment]
@blainekasten donezo: https://github.com/blainekasten/enzyme-matchers/pull/159
