### ISSUE TITLE
React 16 and enzyme 3 compatibility for jest-enzyme

### ISSUE THREAD

**Issue by fernandopasik** [blainekasten/enzyme-matchers#160]
Hi!
[Enzyme 3](https://github.com/airbnb/enzyme/releases/tag/enzyme%403.0.0) and [React 16](https://github.com/facebook/react/releases/tag/v16.0.0) are out now, and trying to use them I'm detecting the following error on my test runs with jest:

`Cannot find module 'enzyme/build/ShallowTraversal' from 'shallow.js'`

I suspect that has something to do with enzyme-to-json being outdated as well, but now [v3.0](https://github.com/adriantoine/enzyme-to-json/releases/tag/v3.0.0) is out.

**Comment by fernandopasik** [comment]
After doing an update of enzyme-to-json to v3.0, some tests run now but a lot of them are throwing this error:

```
Attempted to access ShallowWrapper::nodes, which was previously a private property on
Enzyme ShallowWrapper instances, but is no longer and should not be relied upon.
Consider using the getElements() method instead.
```

**Comment by blainekasten** [comment]
I've been looking at this for the past hour. It's going to take a decent amount of work as many internal things changed.. I should be able to spend a good amount of time tomorrow working on it. So hopefully it'll just take a day or two.

**Comment by csvan** [comment]
+1

**Comment by blainekasten** [comment]
Cutting a release in 2m.

**Comment by blainekasten** [comment]
Try 4.0.0!

**Comment by fernandopasik** [comment]
Thanks for the hard work @blainekasten !! An awesome library you did!!

**Comment by blainekasten** [comment]
❤️
