### ISSUE TITLE
toIncludeText output does not match common style

### ISSUE THREAD

**Issue by blainekasten** [blainekasten/enzyme-matchers#164]
This is `toHaveText`

![image](https://user-images.githubusercontent.com/2916023/31138872-beb73ad0-a824-11e7-83f6-8d4a66474b39.png)

This is `toIncludeText`

![image](https://user-images.githubusercontent.com/2916023/31138884-c7b6c722-a824-11e7-924b-6ac5919c6ae7.png)

`toIncludeText` is missing the Expected/Actual verbage

**Comment by enthudrives** [comment]
@blainekasten I have picked this up.

**Comment by enthudrives** [comment]
@blainekasten Hello, I created a pull request for this issue. Can you please take a look?
