### ISSUE TITLE
Don't specify a version of @types/react

### ISSUE THREAD

**Issue by Vinnl** [blainekasten/enzyme-matchers#166]
I'd have submitted a PR myself, but since there's both a `package-lock.json` and a `yarn.lock`, I'm not quite sure what the correct procedure would be...

Anyway, I'm currently running into a problem where I've upgraded my dependency on `@types/react` locally, but because `jest-enzyme` depends on v15 specifically, I now have duplicate type definitions installed, and TypeScript trips about it.

I'm not entirely sure about the solution, but other typings specify a dependency on `@types/react@*`, i.e. they don't mandate a specific version. Perhaps `jest-enzyme` should do the same.

Another option that I can think of would be to make it a `peerDependency` (and perhaps a `devDependency` as well), but I'm not quite sure whether that would be sufficient to solve the issue - at least not if you'd still define a version for it.

**Comment by blainekasten** [comment]
Hey @Vinnl 

Thanks for the report! I unfortunately don't use Typescript so all of the progress in that area so far has been driven by the community. I'd like to cc a few people to get their thoughts. I'm open to trying anything.

cc @pascalduez @cyberhck @pselden @Dean177

**Comment by blainekasten** [comment]
> I'd have submitted a PR myself, but since there's both a package-lock.json and a yarn.lock, I'm not quite sure what the correct procedure would be...

That is confusing. The ecosystem is in a weird place. I would probably prefer to just have a `yarn.lock`

**Comment by pselden** [comment]
I would move it to a devDependency only and not a peerDependency, as it is not actually _required_ to use types to use this package. As a devDependency you could leave the version the same as it currently is, or just bump it to ^16.0 -- it'd just be for development/testing purposes.

**Comment by blainekasten** [comment]
If it becomes a `devDependency` wouldn't it not get installed into your guys' projects? My understanding of `devDependency` is that it only is activated when you run install from enzyme-matchers package.json's root. Not your project root. Am I wrong in this?

**Comment by pselden** [comment]
Correct, it would not be installed. But I don't see that as a problem since if you're using TypeScript with React you already have @types/react installed in your project.

**Comment by Vinnl** [comment]
It's somewhat required if you are using TypeScript, but yes, you can expect it to be installed if you're using TypeScript and React. Another option might be [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies), but I'm not sure if that wouldn't still result in conflicts.

**Comment by pselden** [comment]
optionalDependencies do get installed as if it were a normal dependency unless you specify --no-optional (which likely no one would). They're more meant for things that could fail installing on a specific platform, but you have a backup for if they do.

Here's an example of a popular TypeScript project for React that just puts it in devDepencies: https://github.com/mobxjs/mobx-react/blob/master/package.json#L38-L39

**Comment by Vinnl** [comment]
OK, `devDependencies` sounds fine then. I tried a PR again, but a `yarn install` is failing for me unfortunately (`sh: 1: babel: not found`)...

**Comment by cyberhck** [comment]
@blainekasten I don't deal with yarn.lock anymore because node 8 is minimum requirements on all our projects now, and npm 5 offers lock functionality. I'd say we can simplify this by removing either package-lock.json or yarn.lock. This way we have one single source of truth. (And it's one less dependency to work with if you decide to remove yarn).

Regarding this issue, I can't give much thoughts because we're still in process of updating react 16 and I don't know of any corner case while upgrading, yet.

I did like the what @pselden commented about mobx-react though. I don't see any downsides with devDependency, it'll install on all developers of enzyme-matchers, which shouldn't be a problem.

**Comment by blainekasten** [comment]
Sweet. So, this is probably annoying. But I want to keep the yarn.lock and npm lock. I don't feel like the community has really sorted out what the best path forward is. I think we can sort that out later and it's not going to hurt really anything for now.

It sounds like it's a good idea to move that into a devDep. Anyone want to submit a PR?

**Comment by Vinnl** [comment]
@blainekasten How do you do that? If I run `yarn` it doesn't update the `package-lock.json` and if I run `npm install` it doesn't update the `yarn.lock`. What tool do you use to keep them in sync? Are they even in sync right now?

(Also: how do you install the dependencies? Is a simple `cd packages/jest-enzyme; yarn` supposed to work? Because it doesn't for me, as mentioned above...)

**Comment by blainekasten** [comment]
@Vinnl I realize that. I'm saying I'm not worried right now if they are not in sync, unless you can think of a dire reason they should be?

> (Also: how do you install the dependencies? Is a simple cd packages/jest-enzyme; yarn supposed to work? Because it doesn't for me, as mentioned above...)

This project is built on [lerna](https://github.com/lerna/lerna#commands).
You should install that globally and run `lerna bootstrap` from the root
it will handle everything

**Comment by Vinnl** [comment]
@blainekasten Well, the entire point of those files is to make sure dependency trees are reproducible, so if they don't represent the actual dependency tree, they don't add anything and are actively confusing - so it might be better just not to check in either.

Anyway, I've created a PR that hopefully addresses the issue in the proper way: #167.

**Comment by cyberhck** [comment]
I agree with @Vinnl here, `package-lock.json` and `yarn.lock` are meant to provide a user to get reproducible dependency tree, if both aren't in sync, we might have a problem. Maybe we can use `npm shrinkwrap` after using yarn to update `package-lock.json`??
