### ISSUE TITLE
Cannot find module 'enzyme/build/ShallowTraversal' from 'shallow.js'

### ISSUE THREAD

**Issue by cyberhck** [blainekasten/enzyme-matchers#170]
with new react and enzyme 16 I'm getting that error. With what I could investigate, I see they removed "ShallowTraversal" file. It's being included in jest-enzyme package. Issue has been discussed at adriantoine/enzyme-to-json#63 and they've got a fix, and latest release is v3.1.3

I'm not 100% sure, but using newer build might just work. :slightly_smiling_face: let me know if you need more details.

**Comment by blainekasten** [comment]
Are you using v4.x of this library? https://github.com/blainekasten/enzyme-matchers/releases

I remember this being a compat issue with v3.x and less. But 4.x should fix it.

**Comment by cyberhck** [comment]
Oh, I am sooo sorry, I didn't realize I wasn't using 4.x version of this library (even though I was at release page, I didn't realize that I didn't realize I wasn't using that one), it's looks like this is fixed in v4.x sorry to bother you

**Comment by blainekasten** [comment]
No problem!
