### ISSUE TITLE
param reassign in stringify.js breaks flow's experimental.const_params

### ISSUE THREAD

**Issue by aaronjensen** [blainekasten/enzyme-matchers#173]
It's experimental and it's easily worked around, so do with this what you will, but in `stringify.js` there's a param reassign, so using this library on a flow enabled repo that has `experimental.const_params = true` errors with:

```
Error: node_modules/enzyme-matchers/lib/utils/stringify.js.flow:13
 13:     value = [];
         ^^^^^ value. const param cannot be reassigned (see experimental.const_params=true in .flowconfig)
  5: function stringifySingle(key: string, value: any): Array<string> {
                                           ^^^^^^^^^^ const param value
```

I've worked around this by ignoring it in my `.flowconfig`:

```
[ignore]
.*/node_modules/enzyme-matchers/lib/utils/stringify.js.flow
```

**Comment by blainekasten** [comment]
Oh cool find! I actually didn't realize we were doing this. It should be fixed. It's a bad practice and can easily lead to bugs. Even noticed we turned off eslint for this specific line :| 
https://github.com/blainekasten/enzyme-matchers/blob/master/packages/enzyme-matchers/src/utils/stringify.js#L12

Would you want to submit a PR to fix it?
