### ISSUE TITLE
what will be the difference between using enzyme directly in jest with import or VS using enzyme-matchers?

### ISSUE THREAD

**Issue by adamchenwei** [blainekasten/enzyme-matchers#185]
I want to see if there is a real need to install this package. Do I really need enzyme-matchers for enzyme to work properly in jest? What would be the problems come up if I dont use this package?

Thanks!

**Comment by adamchenwei** [comment]
more detail

**Comment by blainekasten** [comment]
Hey @adamchenwei this library is not required in any way. It's just a nice add-on to make your tests more readable. 

An example is it can turn this code that checks if a node is rendered:

```
it('renders a specific node', () => {
  const wrapper = shallow(<MyComponent />);
  expect(wrapper.find('div').nodes.length).toBe(1);
});
```

into 

```
it('renders a specific node', () => {
  const wrapper = shallow(<MyComponent />);
  expect(wrapper.find('div')).toBePresent();
});
```

Both are valid code, this library just helps simplify some of your assertions. Hope it helps you! If you use this package though, use the jest-enzyme package, not enzyme-matchers directly.
