### ISSUE TITLE
pretty .html() snapshot

### ISSUE THREAD

**Issue by z-vr** [blainekasten/enzyme-matchers#187]
Hi, I thought that pretty `html()` snapshots were implemented here (https://github.com/airbnb/enzyme/issues/649), but I can't seem to get it working -- I just get a single line in my snapshots. Maybe it's because I'm using `shallow` rendering -- is it possible to implement a formatting for it as well as `mount` please?

**Comment by blainekasten** [comment]
That is a bit misleading. It's not meant to snapshot the html() output, but instead the component.

So you should just do:

```
const wrapper = (mount || shallow)(<Component />);
expect(wrapper).toMatchSnapshot();
```
