### ISSUE TITLE
MATCHER WANTED: `toHaveAttr(key, value)`

### ISSUE THREAD

**Issue by ngthorg** [blainekasten/enzyme-matchers#30]
SPEC:

``` js
const style = { width: '50px', height: '50px' };
const wrapper = shallow(<img alt="avatar" src="image.jpg" style={style} />);

expect(wrapper).toHaveAttr('alt', 'avatar');
expect(wrapper).toHaveAttr('src', 'image.jpg');
expect(wrapper).toHaveAttr('style', 'width:50px;height:50px;');

```

**Comment by blainekasten** [comment]
So, I worked on the code to implement property selectors in Enzyme. Originally it was built to support html attributes also, similar to the matcher your expecting. It was ultimately decided against supporting attributes because that means in some ways, you are testing react itself, and not just your components. 

So with that said, i'm hesitant to take anything around this. But can you explain your reasoning for why you would want this as opposed to just prop assertions?

**Comment by blainekasten** [comment]
Looking for an update @ngthorg, otherwise I'll close this issue.

**Comment by fernandopasik** [comment]
Hi! I see value on testing how provided props can change the component html. Would this not be good candidate to test attributes?

**Comment by blainekasten** [comment]
Both examples still conclude in testing props. When you render an `<input />` in react, you are not actually creating an input.

You are telling React to create an Input. You are describing what you want that input to be and look like. That is the line to draw with your tests.

Easily put:
Your concern: What you are telling React to render.
Not your concern: What React is telling the browser to render.

**Comment by fernandopasik** [comment]
I agree we not need to test what concerns React, but isn't my concern to test if the prop created an attribute in the input node?

I'd like to share an example I have done using chai enzyme.

```
function Field (props) {
  return (
    <div className="field">
      <label htmlFor={props.id}>{props.label}</label>
      <input id={props.id} type={props.type} name={props.name} />
    </div>
  );
}
```
And a test for this:
```
describe('Field', () => {
  it('render', () => {
    const $label = shallow(<Field id="user" label="User Name" name="user" />).find('label');
    expect($label).to.be.present();
    expect($label).to.have.text('User Name');
    expect($label).to.have.attr('for', 'user');
  });
});
```

The only thing I'm missing in jest-enzyme is the toHaveAttr assertion.

**Comment by blainekasten** [comment]
What is the benefit in the unit test of `attr('for', 'user')` vs `prop('htmlFor', 'user')` ?

**Comment by fernandopasik** [comment]
You are right @blainekasten there is no benefit. Thank you for clarifying!!

**Comment by heygrady** [comment]
It's possible to achieve this (even though you don't need to) like this:

```js
const wrapper = render(<FunButton color={SPECIAL} />)
const attributes = wrapper['0'].attribs
expect(attributes).toHaveProperty('data-color', 'green')
```
