### ISSUE TITLE
toHaveText seems like it'll be likely to break; I suggest toIncludeText

### ISSUE THREAD

**Issue by jjinux** [blainekasten/enzyme-matchers#38]
I think the danger with toHaveText is that if you add any more text anywhere else in the component, the test will break. If you add another matcher called toIncludeText that just asserts that the text includes some text, that would be much more resilient to false failures.

**Comment by andrewzielinski** [comment]
I agree with @jjinux. It makes tests extremely brittle

**Comment by blainekasten** [comment]
Sorry for the delay on the response. I'm currently on paternity leave so mostly afk. 

However, this is good conversation. I think you have a good point. I also think in some cases that might be a desired effect for that test to break. The point of tests are for them to break. 

I think it might be a good idea to support both cases though and let users decide what makes sense for them. Would you want to put up a PR for adding that marcher?

**Comment by jjinux** [comment]
> I'm currently on paternity leave so mostly afk.

Congrats! I actually have 8 kids ;)

> I think it might be a good idea to support both cases though and let users decide what makes sense for them.

Yes. That's why I was advocating for adding a new matcher.

> Would you want to put up a PR for adding that marcher?

Ok.

**Comment by blainekasten** [comment]
Dang! 8 sounds intense right now. Haha. Looking forward to the PR

**Comment by blainekasten** [comment]
@jjinux were you still planning on adding this?

**Comment by jjinux** [comment]
It should be done, but I just haven't had time to do it. I suck.

**Comment by jjinux** [comment]
I may be confused, but it looks like it already exists :-/

**Comment by jjinux** [comment]
Sorry, never mind.

**Comment by jjinux** [comment]
@blainekasten, here's a PR: https://github.com/blainekasten/enzyme-matchers/pull/49
