### ISSUE TITLE
Future Plans

### ISSUE THREAD

**Issue by blainekasten** [blainekasten/enzyme-matchers#39]
Jest is diverging from jasmine slowly, so we need to prepare for that change. My plan is this:

- [x] convert repo to multi-repo with lerna
- [x] rename repo to `enzyme-matchers`. Different name?

*packages would be:*
- enzyme-matchers 
- jasmine-enzyme
- jest-enzyme

Could be extensible for mocha, chai, Ava, etc with this approach

**Comment by blainekasten** [comment]
Is anything directly changing with the addMatcher API?

cc @cpojer / @dmitriiabramov

**Comment by cpojer** [comment]
See https://github.com/facebook/jest/issues/1835 Please help us out!
