### ISSUE TITLE
toContainReact failure message is inverted

### ISSUE THREAD

**Issue by mewdriller** [blainekasten/enzyme-matchers#47]
It looks like the assertion failure message for `toContainReact` is inverted.

### Expected

```
FAIL  src\App.test.js
  ● <App/> › renders the welcome message

    Expected wrapper to contain <h2>THE CORRECT MESSAGE</h2>.

      at stack (node_modules\jest-jasmine2\vendor\jasmine-2.4.1.js:1580:17)
      at Object.it (src\App.test.js:10:21)
      at process._tickCallback (internal\process\next_tick.js:103:7)
```

### Actual

```
FAIL  src\App.test.js
  ● <App/> › renders the welcome message

    Expected wrapper not to contain <h2>THE CORRECT MESSAGE</h2>.

      at stack (node_modules\jest-jasmine2\vendor\jasmine-2.4.1.js:1580:17)
      at Object.it (src\App.test.js:10:21)
      at process._tickCallback (internal\process\next_tick.js:103:7)
```

It's a little subtle, but the error message is saying that it expected to the component *not* to contain a snippet of JSX. In this case, the expectation was that it *does* contain that snippet.

### Steps to Reproduce

1. Use the `create-react-app` boilerplate and add `jest-enzyme` to it. 
2. Alter the included `App.test.js` slightly (see below)
3. Run `npm test`.

```
// src/App.test.js

import { shallow } from 'enzyme';
import React from 'react';
import App from './App';

describe('<App/>', () => {
  it('renders the welcome message', () => {
    const wrapper = shallow(<App/>);
    const message = <h2>THE CORRECT MESSAGE</h2>;

    expect(wrapper).toContainReact(message);
  });
});
```

**Comment by mewdriller** [comment]
Digging in a little, it looks like maybe [this line](https://github.com/blainekasten/enzyme-matchers/blob/v2.0.0/packages/enzyme-matchers/src/assertions/toContainReact.js#L20) shouldn't use  the `negateMessage` helper. But given that it's there, I'm assuming there's another situation that I'm not considering.

**Comment by blainekasten** [comment]
This is on the latest version?

**Comment by mewdriller** [comment]
I'm seeing the behavior on `v2.0.0`, which I believe is the latest.

**Comment by blainekasten** [comment]
Yeah. Looking into this more, I think I made a mistake and every matcher has an inverted message :\ 

I'm going to work on this in the next week.

**Comment by jagregory** [comment]
I think you're correct in your assessment, I was just about to report that `toHaveProp` has the same inverted behaviour.

```js
expect(component).toHaveProp('name', 'blah')
```

Produces:

```
Expected wrappers prop values not to match for key "name":
```

**Comment by blainekasten** [comment]
Yeah. Thanks for the report. I have a branch I'm working on to fix this. It's just taking a long time with other initiatives happening! ha
