### ISSUE TITLE
toHaveProp does not respect propValue in 2.1.0-rc1

### ISSUE THREAD

**Issue by mewdriller** [blainekasten/enzyme-matchers#50]
With the following spec:

```jsx
import { shallow } from 'enzyme';
import React, { PropTypes } from 'react';

function User(props) {
  return (
    <div className="user">{props.name}</div>
  );
}

User.propTypes = {
  name: PropTypes.string.isRequired,
};

function Fixture(props) {
  return (
    <div id="root">
      <User name="Nope!" />
    </div>
  );
}

it('should pass props to the User', () => {
  const wrapper = shallow(<Fixture />);

  expect(wrapper.find(User)).toHaveProp('name', 'Test User');
});
```

As of `v2.0.0` the output of the above spec fails and outputs:

```jsx
Expected wrappers prop values not to match for key "name":
            Actual: "Nope!"
            Expected: "Test User"
```

After the upgrade to `v2.1.0-rc1` the spec passes.

**Comment by blainekasten** [comment]
Wait, are you saying that 2.1.0-rc1 fixes the behavior currently broken in 2.0.0?

**Comment by dmiller-nj** [comment]
Sorry for the confusion. I'm trying to say that `2.1.0-rc1` is broken. Reverting to `2.0.0` resolves the issue.

**Comment by mewdriller** [comment]
Sorry for the confusion. I'm trying to say that `2.1.0-rc1` is broken. Reverting to `2.0.0` resolves the issue.

**Comment by blainekasten** [comment]
Awesome! Thanks so much for reporting the issue! I'll try and get it fixed and get a new rc out

**Comment by blainekasten** [comment]
Figured this out! Thanks so much. That was a very real bug that I introduced! haha. Going to close this out. I'll publish a new RC in a little while and probably publish a 2.1.0 later today
