### ISSUE TITLE
Dynamic require statements fail webpack build

### ISSUE THREAD

**Issue by ericontilt** [blainekasten/enzyme-matchers#53]
My webpack build throws warnings when importing jasmine-enzyme because of the colors package imported by enzyme-matchers.

There are two files in which produce the warnings: colors/lib/colors.js (line 138) and colors/lib/extendStringPrototype.js (line 101). Both lines do a dynamic require of some module.

Since the colors package is last updated about a year ago, I don't understand why it's giving me this problem all of the sudden. I'm asking the question here since it's loaded as a dependency of enzyme-matchers. Since so many people are using webpack with jasmine, my assumption is that it's perhaps some sort of configuration issue.

Any ideas as to what might be the problem?

**Comment by blainekasten** [comment]
Hmmm. I could drop the dependency and just make the colors myself. Wouldn't be too hard.

Would you be willing to submit a PR to do that?

**Comment by ericontilt** [comment]
Sure, I'll have a look

**Comment by blainekasten** [comment]
Hey @ericontilt, I just published a potential fix for this under `2.1.2-beta1` could you give it a shot?

**Comment by ericontilt** [comment]
Thanks man. I'll give it a go tomorrow!

**Comment by ericontilt** [comment]
Yup, that fixed it! Thanks!

And by the way, sorry for not submitting the pull request on time..

**Comment by blainekasten** [comment]
`2.1.2` stable is released
