### ISSUE TITLE
jest-enzyme setupTestFrameworkScriptFile needs <rootDir>

### ISSUE THREAD

**Issue by miguel-orange** [blainekasten/enzyme-matchers#54]
I get the below error with ` "setupTestFrameworkScriptFile": "node_modules/jest-enzyme/lib/index.js"`. I no longer have an error when prepending `<rootDir>`.

`Error: Jest: Module "node_modules/jest-enzyme/lib/index.js" in the "setupTestFrameworkScriptFile" option was not found.
    at resolve (.../node_modules/jest-config/build/normalize.js:48:11)
    at Object.keys.reduce (.../node_modules/jest-config/build/normalize.js:343:17)
    at Array.reduce (native)
    at normalize (.../node_modules/jest-config/build/normalize.js:294:23)
    at promisify.then (.../node_modules/jest-config/build/loadFromPackage.js:24:12)
error Command failed with exit code 1.`

**Comment by blainekasten** [comment]
what version of jest? I think old versions of jest required rootDir, newer ones shouldn't.

**Comment by blainekasten** [comment]
though it's likely worth documenting both cases if confirmed.

**Comment by miguel-orange** [comment]
@blainekasten Jest version: 18.1.0
Maybe an issue with Jest? I was able to set `snapshotSerializers` successfully without `<rootDir>`.

**Comment by blainekasten** [comment]
Well that's good to know. Would you mind submitting a PR to update the documentation?

**Comment by pascalduez** [comment]
Since Jest 18 `setupTestFrameworkScriptFile` paths are fully resolved.

So one could also just update to:
```json
"setupTestFrameworkScriptFile": "./node_modules/jest-enzyme/lib/index.js"
```

**Comment by blainekasten** [comment]
I've updated the readme for jest-enzyme. Thanks guys
