### ISSUE TITLE
Issue with assertions calling html() for contextualInformation

### ISSUE THREAD

**Issue by rtymchyk** [blainekasten/enzyme-matchers#65]
I'm noticing that most of the assertions perform an `html()` invocation on the enzyme wrapper (to generate possible error output?). This triggers a `renderToStaticMarkup` from `react-dom`, which seems to defeat the whole purpose of shallow rendering because this tries to build the full tree and fails because dependencies of children in the tree are not met.

Am I missing something obvious?

**Comment by blainekasten** [comment]
That's a dang good question. I think you are onto something impressive.

I'll look into this when I get a chance. If you can find a fix for this I'd likely take it. I never thought that through!

**Comment by rtymchyk** [comment]
It seems like we can swap some of those out with [debug()](http://airbnb.io/enzyme/docs/api/ShallowWrapper/debug.html#-debug-string) from Enzyme instead, so we get similar HTML-like output. 

I can probably get something working with that, but let me know what you find :)

**Comment by rtymchyk** [comment]
Hey @blainekasten, wanted to check in and see if you had a chance to take a closer look at this. No rush, just a friendly reminder :)

**Comment by blainekasten** [comment]
I have not had a chance. My life is super busy and demanding right now... If you want to put up a PR simple swapping `html` for `debug` that'd probably be the easiest way to move forward. Thanks for checking in

**Comment by rtymchyk** [comment]
Sounds good, thanks.

**Comment by blainekasten** [comment]
I think ideally we would want to call `html` on mount wrappers` and `debug` on shallow now that I think about it. So let's try and do that.

**Comment by blainekasten** [comment]
This is now published on a major bump, 3.0.0
