### ISSUE TITLE
`toHaveState` with stateValue passes when it shouldn't

### ISSUE THREAD

**Issue by martingordon** [blainekasten/enzyme-matchers#66]
`toHaveState` appears to be ignoring the second argument (stateValue) as described here: https://github.com/blainekasten/enzyme-matchers#tohavestatestatekeystring-statevalueany

Since it's ignoring the second argument, tests pass if they will likely have the key even if the values don't match. Here's a reduced test case:

```js
import React from 'react';
import { shallow } from 'enzyme';

class Fixture extends React.Component {
  constructor() {
    super();
    this.state = { foo: 12 };
  }

  render() {
    return (<div />);
  }
}

describe('test', () => {
  it('should fail', () => {
    const wrapper = shallow(<Fixture />);

    // This should fail since 12 != 15
    expect(wrapper).toHaveState('foo', 15);
  });
});
```

**Comment by blainekasten** [comment]
Yikes! That's not good. Would you be willing to try and submit a PR to fix it? 

The code is here: https://github.com/blainekasten/enzyme-matchers/blob/master/packages/enzyme-matchers/src/assertions/toHaveState.js
and the tests are here: https://github.com/blainekasten/enzyme-matchers/blob/master/packages/enzyme-matchers/src/assertions/__tests__/toHaveState--tests.js

**Comment by blainekasten** [comment]
@martingordon I just tested this in latest and it seems to be working. Can you confirm it's still an issue?

**Comment by blainekasten** [comment]
I'm going to close this. If you are experiencing this on latest, please respond and we'll re-open it.

**Comment by martingordon** [comment]
Thanks. Haven't had a chance to test it yet, but will keep an eye out for it to see if it is still an issue once we get around to upgrading to latest.
