### ISSUE TITLE
TypeError: expect.addSnapshotSerializer is not a function

### ISSUE THREAD

**Issue by mruzekw** [blainekasten/enzyme-matchers#71]
I receive the following error when I try to run my tests with `jest-enzyme`:
```
TypeError: expect.addSnapshotSerializer is not a function
```

**Comment by blainekasten** [comment]
I'm assuming you ignored the npm peer dependency warnings :)

Jest added this feature in version 19 hence this [https://github.com/blainekasten/enzyme-matchers/blob/master/packages/jest-enzyme/package.json#L46](peer dep).

You either need to upgrade jest or use a 2.x version of jest-enzyme that supports older versions of jest.

**Comment by andrei-e-random** [comment]
Created a PR to add what you mentioned in the README. 

I'm expecting people new to the ecosystem to use create-react-app a lot and stumble upon enzyme eventually. And I'm not really expecting many of them to read peer dependency warnings :).

**Comment by blainekasten** [comment]
Awesome! Thanks so much!
