### ISSUE TITLE
`toHaveTagName` does not work in IE11

### ISSUE THREAD

**Issue by juanca** [blainekasten/enzyme-matchers#81]
Running my spec suite on Chrome, Firefox, Safari, Edge, and IE11. 

IE11 is the only browser experiencing the following:

```
Expected <function DropContainer(props) {
	  var className = props.className,
	      direction = props.direction,
	      flush = props.flush;


	  return _react2.default.createElement(
	    _reactAddonsTransitionGroup2.default,
	    {
	      className: className + ' ' + directionClassName(direction) + ' ' + flushClassName(flush, direction),
	      component: 'div'
	    },
	    props.children
	  );
	}> node to equal (using ===) type "ReactTransitionGroup" but it is a "undefined".
```

where 

```
export default function DropContainer(props) {
  const {
    className,
    direction,
    flush,
  } = props;

  return (
    <ReactTransitionGroup
      className={`${className} ${directionClassName(direction)} ${flushClassName(flush, direction)}`}
      component="div"
    >
      {props.children}
    </ReactTransitionGroup>
  );
}
```

Stepping through the matcher, it's pretty clear why it would be failing. 

Attempting to get the name of the [enzymeWrapper](https://github.com/blainekasten/enzyme-matchers/blob/84362f841c147869296dade8d87a43bfdfbab47e/packages/enzyme-matchers/src/assertions/toHaveTagName.js#L19) is [not supported in IE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name).

A polyfill should suffice. I'll see if I can provide a workaround (for the time being).

**Comment by juanca** [comment]
Looks like `enzymeWrapper.name()` should work. Would that be preferable over `type().name`?

**Comment by blainekasten** [comment]
I think `.name()` should be fine. Mind submitting a PR? If it passes the tests without any changes I would say it's a safe assumption
